import esbuild from "esbuild";

const isProd = process.argv.includes("--production");
const isWatch = process.argv.includes("--watch");

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source visit the plugins github repository
*/
`;

/** @type {import("esbuild").BuildOptions} */
const buildOptions = {
  banner: { js: banner },
  entryPoints: ["src/bf-main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
  ],
  format: "cjs",
  outfile: "build/main.js",
  sourcemap: isProd ? false : "inline",
  minify: isProd,
  target: "es2018",
  logLevel: "info",
};

if (isWatch) {
  const ctx = await esbuild.context(buildOptions);
  await ctx.watch();
  console.log("Watching for changes...");
} else {
  await esbuild.build(buildOptions);
}
